"use client";
import { useMemo, useState } from 'react';
import type { InteractiveModel as InteractiveModelData } from '@/lib/interactive-model';
import { defaultControls, simulateModel } from '@/lib/interactive-model';
export function InteractiveModel({ model, onActivity = () => {} }: { model: InteractiveModelData; onActivity?: (text: string) => void }) {
  const [controls, setControls] = useState(defaultControls(model)); const [step, setStep] = useState(model.duration);
  const run = useMemo(() => simulateModel(model, controls), [model, controls]); const frame = run.frames[Math.min(step, run.frames.length - 1)] ?? {}; const max = Math.max(1, ...model.stocks.flatMap(s => run.frames.map(f => Math.abs(f[s.id] ?? 0))));
  return <div className="interactive-model" aria-label="可调参数模拟器"><div className="model-rule"><strong>先改一个条件，再看它怎样展开</strong><p>{model.rules}</p><small>{model.assumptions}</small></div><div className="model-controls">{model.controls.map(c => <label key={c.id}><span>{c.label} <small>{c.unit}</small></span><input type="range" min={c.min} max={c.max} step={c.step} value={controls[c.id]} onChange={e => { setControls(v => ({...v,[c.id]:Number(e.target.value)})); setStep(model.duration); onActivity('已调整参数，可以单步观察变化。'); }}/><output>{controls[c.id]}</output></label>)}</div><div className="model-chart" aria-label={`第 ${step} ${model.stepLabel}`}><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 160H600" stroke="currentColor" opacity=".15"/>{model.stocks.map((s,si)=><polyline key={s.id} fill="none" stroke={['#1683ff','#f97316','#16a37a'][si]} strokeWidth="3" points={run.frames.map((f,i)=>`${i/(Math.max(1,run.frames.length-1))*600},${160-(Number(f[s.id]??0)/max)*130}`).join(' ')}/>)}</svg><div className="model-readout"><strong>第 {step} {model.stepLabel}</strong>{model.stocks.map(s=><span key={s.id}>{s.label}：{Number(frame[s.id]??0).toFixed(1)} {s.unit}</span>)}</div></div><div className="model-actions"><button className="button" onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0}>← 单步后退</button><button className="button primary" onClick={()=>{setStep(s=>Math.min(model.duration,s+1));onActivity('已向前推进一步。')}} disabled={step===model.duration}>单步前进 →</button><button className="text-button" onClick={()=>setStep(model.duration)}>跑到结果</button></div>{run.error&&<p className="error-message">{run.error}</p>}</div>;
}
